{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "SubmitBox"
	},
	"OnFailure": "/PackedBoxTracking/Rules/SubmitBoxFailure.js",
	"OnSuccess": "/PackedBoxTracking/Actions/SubmitSuceessMessage.action",
	"ValidationRule": "/PackedBoxTracking/Rules/ValidateBoxData.js",
	"ShowActivityIndicator": true,
	"Target": {
		"Service": "/PackedBoxTracking/Services/TRACKING.service",
		"EntitySet": "BoxDetailsSet"
	},
	"Properties": {
		"BoxId": "#Page:Main/#Control:BoxId/#Value",
		"LicensePlate": "#Page:Main/#ClientData/InvDetail/LicensePlate",
		"InvoiceNo": "#Page:Main/#Control:InvNo/#Value",
		"LabelId": "#Page:Main/#Control:LabelId/#Value",
		"LicensePlate1": "#Page:Main/#Control:LicensePlate1/#Value",
		"LicensePlate2": "#Page:Main/#Control:LicensePlate2/#Value",
		"LicensePlate3": "#Page:Main/#Control:LicensePlate3/#Value",
		"LicensePlate4": "#Page:Main/#Control:LicensePlate4/#Value",
		"BoxQty": "#Page:Main/#ClientData/InvDetail/BoxQty",
		"OkFlag": "",
		"UserName": "",
		"Matnr": "#Page:Main/#ClientData/InvDetail/Matnr"
	},
	"Headers": {
		"loginType": "/PackedBoxTracking/Rules/SetLoginTypeHeader.js",
		"loginId": "/PackedBoxTracking/Rules/SetLoginIdHeader.js"
	}
}